"Secure_Configure_version: 'True' " 
"updates:'Auto_Configure_According_To_Resources'"
"Set-Package-ecosystem:'Auto_Configure_According_To_Resources'"
"Directory:'Auto_Configure_According_To_Resources'"
"Default_Rebase_strategy: 'Enabled'
"schedule:NO"
"Interval: NO"
"Commit:Message"
"'Prefix:Security'" 
" 'Open-pull-requests-limit: #only_check_security_updates'"
